import type {Metadata} from "next";
// import localFont from "next/font/local";
import './global.css';

// const geistSans = localFont({
//     src: "./fonts/GeistVF.woff",
//     variable: "--font-geist-sans",
//     weight: "100 900",
// });
// const geistMono = localFont({
//     src: "./fonts/GeistMonoVF.woff",
//     variable: "--font-geist-mono",
//     weight: "100 900",
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <div className="header">
            <img
                src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Commerzbank_%282009%29.svg/2560px-Commerzbank_%282009%29.svg.png"
                alt="Commerzbank Logo"
            />
            <nav>
                <a href="#">Konten & Zahlungsverkehr</a>
                <a href="#">Finanzierungen & Außenhandel</a>
                <a href="#">Anlagen & Risikomanagement</a>
                <a href="#">Services</a>
                <a href="#">Meine Daten</a>
                <a href="#">Hilfe</a>
            </nav>
        </div>

        {children}

        <footer>© 2024 Commerzbank AG</footer>
        </body>
        </html>
    );
}
